FROM debian:stretch

MAINTAINER Bruno Perel <brunoperel@gmail.com>

RUN set -ex \
    && mkdir -p /uploads /etc/apt/sources.list.d /var/cache/apt/archives/ \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get clean \
    && apt-get update -y \
    && apt-get install -y \
        bash \
        openjdk-8-jre-headless \
    && apt-get clean

WORKDIR /home

CMD java -cp 'jars/*' org.languagetool.server.HTTPServer --port 8010 --public --allow-origin '*' --config db.properties
EXPOSE 8010